### PR TITLE
Installer script

### PR DESCRIPTION
**Pull request by cmaujean**
basic curl based install script with support for linux (non-deb/non-rpm) and for the "portable" version.

### CODE REVIEW

**Comment by erikh** [comment]
Can one of the admins verify this patch?

**Comment by erikh** [comment]
Can we template the script instead of having the `LATEST` file?

e.g.,

```
curl -sSL 'http://.../@@VERSION@@'
```

and in release.sh:

```
sed -e "s/@@VERSION@@/${1}/g" installer.sh.tmpl
```

**Comment by cmaujean** [comment]
I thought the LATEST file was a more succinct and easy path to take, but I guess we could. We had talked about avoiding templating it, so I thought of using the file.

**Comment by erikh** [comment]
Hmm ok. I guess I misunderstood. Let's template the default version and
leave out the LATEST file, it will be an artifact in the repo that will not
be worth maintaining.

**Comment by erikh** [comment]
can you squash?

**Comment by erikh** [comment]
also please sign your commits by passing the -s flag:

```
git commit -a -s --amend
```

**Comment by erikh** [comment]
carried in #186 so I can get the squash and signatures.

**Pull request closed without merging**
